### ISSUE TITLE
Slight mismatch in the buffer name's background color

### ISSUE THREAD

**Issue by asos-stephanemaniaci** [tarsius/minions#11] opened 2018-04-23 16:18 UTC
I cannot find which font override I'm missing, but I can't get the area below the diagonal strokes to match the active tab's colour. Here's a screenshot that will hopefully explain it better:

<img width="216" alt="screen shot 2018-04-23 at 17 11 07" src="https://user-images.githubusercontent.com/34539260/39139256-53051426-4719-11e8-9fd3-8f9a5a763be3.png">

Can you think of why that would be? Sorry for not providing much but I'm not very good with the under-the-hood parts of Emacs.

I'm using Solarized Light with the instructions in the README. Emacs version is:

`GNU Emacs 26.0.50 (build 2, x86_64-apple-darwin16.4.0, NS appkit-1504.81 Version 10.12.3 (Build 16D32)) of 2017-09-13`.

Thanks!

**Comment by tarsius** [comment] 2018-04-23 17:29
That's the wrong repository and likely a duplicate of https://github.com/tarsius/moody/issues/2.

**Closed by tarsius** 2018-04-23 17:29 UTC

**Comment by asos-stephanemaniaci** [comment] 2018-04-24 08:08
Whoops, so sorry was toying around with both projects and got confused.
