### ISSUE TITLE
`*invalid*` is appended to the minor mode name with some prominent modes

### ISSUE THREAD

**Issue by jpalaciosdev** [tarsius/minions#38] opened 2023-02-28 19:20 UTC
![minions-prominent-ovwrt-mode](https://user-images.githubusercontent.com/10498177/221955113-7e79fd83-0edb-4e2d-84f9-ead716aa38f8.png)

It can be reproduced by adding `overwrite-mode` to `minions-prominent-modes`:
```
(setq minions-prominent-modes (list 'overwrite-mode))
```

The change that triggered such behaviour is [this one](https://github.com/tarsius/minions/commit/7a12d3ed358dfd47fdd09655954d518f67b5c68b#diff-d24579212921d654701ef88c75410730ac391cabd565f6eb241ea92d2e02f271R202). Restoring it to `(memq (car mode) minions-prominent-modes))` fixes the issue.

**Comment by tarsius** [comment] 2023-02-28 19:42
Duplicate of #37.

**Closed** 2023-02-28 19:42 UTC
Labels: duplicate
